ALTER SERVER ROLE [sysadmin] ADD MEMBER [DESKTOP-964U6AM\USER];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLWriter];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\Winmgmt];

