GreyBass::Grey_Bass::Grey_Bass
GreyBass.Grey_Bass.Grey_Bass::_externalFactor
Referenced by GreyBass.Grey_Bass.Grey_Bass._NLS, GreyBass.Grey_Bass.Grey_Bass._whitenisation, GreyBass.Grey_Bass.Grey_Bass.predict.
GreyBass.Grey_Bass.Grey_Bass::_internalFactor
Referenced by GreyBass.Grey_Bass.Grey_Bass._NLS, GreyBass.Grey_Bass.Grey_Bass._whitenisation, GreyBass.Grey_Bass.Grey_Bass.predict.
GreyBass.Grey_Bass.Grey_Bass::_marketSize
Referenced by GreyBass.Grey_Bass.Grey_Bass._NLS, GreyBass.Grey_Bass.Grey_Bass._whitenisation, GreyBass.Grey_Bass.Grey_Bass.predict.
GreyBass.Grey_Bass.Grey_Bass::_baseSeq
Input check ##.
Nonlinear least square ##
Referenced by GreyBass.Grey_Bass.Grey_Bass.__objFunction, GreyBass.Grey_Bass.Grey_Bass._NLS.
def GreyBass.Grey_Bass.Grey_Bass.__init__
def GreyBass.Grey_Bass.Grey_Bass.predict
References GreyBass.Grey_Bass.Grey_Bass._agoSeq, GreyBass.Grey_Bass.Grey_Bass._externalFactor, GreyBass.Grey_Bass.Grey_Bass._internalFactor, GreyBass.Grey_Bass.Grey_Bass._marketSize, GreyBass.Grey_Bass.Grey_Bass._meanSeq, GreyBass.Grey_Bass.Grey_Bass._whitenisation.
def GreyBass.Grey_Bass.Grey_Bass.rmse
def GreyBass.Grey_Bass.Grey_Bass._meanSeq
References GreyBass.Grey_Bass.Grey_Bass._agoSeq.
Referenced by GreyBass.Grey_Bass.Grey_Bass.__objFunction, GreyBass.Grey_Bass.Grey_Bass.predict.
def GreyBass.Grey_Bass.Grey_Bass._agoSeq
Referenced by GreyBass.Grey_Bass.Grey_Bass._meanSeq, GreyBass.Grey_Bass.Grey_Bass.predict.
def GreyBass.Grey_Bass.Grey_Bass._NLS
References GreyBass.Grey_Bass.Grey_Bass.__objFunction, GreyBass.Grey_Bass.Grey_Bass._baseSeq, GreyBass.Grey_Bass.Grey_Bass._externalFactor, GreyBass.Grey_Bass.Grey_Bass._internalFactor, GreyBass.Grey_Bass.Grey_Bass._marketSize.
def GreyBass.Grey_Bass.Grey_Bass.__objFunction
References GreyBass.Grey_Bass.Grey_Bass._baseSeq, GreyBass.Grey_Bass.Grey_Bass._meanSeq.
Referenced by GreyBass.Grey_Bass.Grey_Bass._NLS.
def GreyBass.Grey_Bass.Grey_Bass._whitenisation
References GreyBass.Grey_Bass.Grey_Bass._externalFactor, GreyBass.Grey_Bass.Grey_Bass._internalFactor, GreyBass.Grey_Bass.Grey_Bass._marketSize.
Referenced by GreyBass.Grey_Bass.Grey_Bass.predict.